obj-m := Tea5767_driver.o

#export GR_FLOAT_FLAGS += -fno-builtin -ffreestanding -msoft-float -mtune=generic

#all:
#	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
#clean:
#	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
