obj-y := lcd_driver.o
lcd_driver-objs := lcd_spi_ctrcl.o lcdILI9341.o 

#all:
#	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
#clean:
#	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
		
