obj-y += ir_decoder_input_driver.o
obj-y += demo_input_driver.o

#all:
#	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
#clean:
#	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
